Version 16.3.11

{============================= Main Part ======================================}
[general]
                    File = /Users/raisor/inflight/lise_files/e_infl_li7_be7_14MeVu_Be.lpp
                    Date = 20-11-2023
                    Time = 09:59:14
           Configuration = other\e_AIRIS.lcn
             Optionsfile = A1900_2016.lopt
                   Title = e_AIRIS
          BlockStructure = DSSSSSSDSSDSSFFASWSSDSSDSSSSSSFFFSMMMMMM
          NumberOfBlocks = 40

[settings]
                   A,Z,Q = 18O 7+                                ; Mass ElementName Charge+ Beam
                  Energy = 13.614650293         MeV/u            
               Intensity = 200                  pnA              ; enA,pna,pps,kW
            RF frequency = 20                   MHz              
            Bunch length = 1                    ns               
         Settings on A,Z = 20O                                   ; Mass ElementName Charge+ Beam

[OpticsBeam]
                      BX = 1                    (+/-)mm          ; one-half the horisontal beam extent (x)
                      BT = 3                    (+/-)mrad        ; one-half the horisontal beam divergence(x')
                      BY = 1                    (+/-)mm          ; one-half the vertical beam extent (y)
                      BF = 3                    (+/-)mrad        ; one-half the vertical beam divergence (y')
                      BL = 0                    (+/-)mm          
                      BD = 0.05                 (+/-)%           ; one-half of the momentum spread (dp/p)
                  ShiftX = 0                    mm               ; beam respect to the spectrometer axis
                  AngleX = 0                    mrad             ; beam respect to the spectrometer axis
                  ShiftY = 0                    mm               ; beam respect to the spectrometer axis
                  AngleY = 0                    mrad             ; beam respect to the spectrometer axis
            Scheme Angle = 0                    degrees          
                  ShapeX = 1
                  ShapeT = 1
                  ShapeY = 1
                  ShapeF = 1
                  ShapeL = 1
                  ShapeD = 1
               OptBeam_X = 1                    (+/-)mm          
               OptBeam_T = 40                   (+/-)mrad        
               OptBeam_Y = 1                    (+/-)mm          
               OptBeam_F = 40                   (+/-)mrad        
               OptBeam_L = 0                    (+/-)mm          
               OptBeam_D = 1                    (+/-)%           

[options]
               NP simple = 64                                    ; Number of points in distribution
        NP charge states = 64                                    ; Number of points in distribution
                NP wedge = 32                                    ; Number of points in distribution
           Charge states = Yes                                   ; No  & Yes
           CutEdgeEffect = 1                                     ; 1-Yes. Default, 0-no - for extended configurations
       Prim.beam scatter = 0                                     ; 0-without, 1-with
              Delta peak = 0                                     ; 0-without, 1-with
             BrhoMeanMax = 0                                     ; 0-Max, 1-Mean
            BrhoMeMaLeRi = 1                                     ; 0-Max, 1-Mean, 2-Left, 3-Right /for fission/

[target]
         Target contents = 0,4,2,9.012                           ; Nomer,Z,Atoms,Mass
        Target thickness = 1,12,1.848,0,0,0                      ; State,Thickness,density,angle,SolidGas,..
  Target fusion compound = 0
   Targ use for Q-states = 1
           Target Defect = 0,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
       Degrader contents = 0,27,42,58.933                        ; Nomer,Z,Atoms,Mass
       Degrader contents = 1,24,20,51.996                        ; Nomer,Z,Atoms,Mass
       Degrader contents = 2,28,13,58.69                         ; Nomer,Z,Atoms,Mass
       Degrader contents = 3,26,19,55.847                        ; Nomer,Z,Atoms,Mass
       Degrader contents = 4,74,1,183.85                         ; Nomer,Z,Atoms,Mass
      Degrader thickness = 1,0,8.3,0,0,0                         ; State,Thickness,density,angle,SolidGas,..
  Degra use for Q-states = 1
         Degrader Defect = 0,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 

[mechanism]
                Reaction = 7                                     ; 0 - fragm, 1 - fusion-resid, 2 - fusion-fission
               CalcOther = 128                                   ; calculate other reactions
           V calculation = 3                                     ; 0 - constant, 1 - Borrel, 2 - Rami, 3-convolution, 4-two body reaction
             V_opt/Vbeam = 1                                     ; default 1
         Velocity_exceed = 1                                     ; 0 - without, 1-with - two-body recations velocity corrections
Binding Energy for Vf/Vp = 8                    MeV              ; Binding energy for Borrel's expression
    Shift for Vf/Vp calc = 0     
        Prefragment_Rami = 1
                  Sigma0 = 90                   MeV/c            ; default 90
                  SigmaD = 200                  MeV/c            ; default 200
                  SigmaM = 87                   MeV/c            ; default 87
               Asymmetry = 0                    %                ; default 0
          Method v-sigma = 3                                     ; 0 - Goldhaber, 1-Morrissey,2-Friedman,3-Convolution
               G_Surface = 0.95                 MeV/fm^2         
 Symmetry around half_Ab = 1
 Pfaff pickup correction = 1
     ChargeExchangePfaff = 1                                     ; 1 - exclude, 0-forget
            Sigma corr 0 = 0                                     ; Coulomb energy
            Sigma corr 1 = 0                                     ; Projectile mass
           Friedman mode = 2                                     ; 0-Qgg, 1-Surface, 2-Qgg+Surface
         Prefragment_Fri = 1
        Coulomb_Friedman = 1
                  K_Morr = 8                    MeV/A            ; E/A=8MeV/A default; D.Morrissey coef.
               K_MorHalf = 8                    MeV/A            ; E/A=8MeV/A default at Afrag=Aproj/2; D.Morrissey coef.
                 AA_fast = 0
               MethodApf = 2                                     ; Prefragment search method: 0-N/Z direction, 1 -  W*EPAX, 2 -  W*CSgeom,
           ExcitationApf = 1                                     ; Excitation energy for APF search: 0 - dSurface, 1 - dA*Ex
            BarrierShape = 1                                     ; 0-classical, 1-quantum mech.
                 H_omega = 5                    MeV              ; default 3
           Probabilty_CN = 1                                     ; 0/1 use Prbabilty for CN formation
            UseVanishing = 1
              VanishMode = 1                                     ; 0-Sierk, 1-Cohen
           NuclPotential = 1                                     ; 0-Bass, 1-WS
                   WS_V0 = 105                  MeV              
                   WS_R0 = 1.12                 fm               
                    WS_a = 0.75                 fm               
          FusDiffuseness = 1    
              Width Coef = 1                                     ; default 1; for Leon's charge state distribution
          gZt Correction = 1                                     ; default 1;      Leon's C.S.D.
           PowerCoefLeon = 0.477                                 ; default 0.477; Leon's C.S.D.
           Cross section = File                                  ; Fit  & File
           Charge method = 5                                     ; charge calculations method  0-5
      EPAX Cross Section = 4                                     ; cross section calculations method 0-4
        SR Cross Section = 2                                     ; EPAX for SR  0-2
             Energy Loss = 0                                     ; energy loss calculation method 0-3
     Anglular straggling = 2
        AngStragInOptics = 1                                     ; 0-LISE, 1-ATIMA
         StragglingCoef1 = 0.217
         StragglingCoef2 = 1.12 
       Energy straggling = 0                                     ; 0-LISE, 1-ATIMA
       EnergyStragMethod = 0                                     ; 0-integrate, 1-table
        EnergyStragShape = 0                                     ; 0-Gauss, 1-Landau-Vavilov
          EquilThickness = 1                                     ; 0-Charge, 1-Global
              MassMethod = 0                                     ; 0-DB+calcul, 1 + just calcul
            MassDataBase = 0                                     ; 0-A&W, 1-User ME
            Mass formula = 1                                     ; 0-LDM, 1-Myerer, 2: 1+corrections
      UseChargeForEnergy = 2                                     ; 0-No, 1-Yes, 2-Auto
         EnergyValueAuto = 30                                    ; default value 30 MeV/u
         EquilibriumMode = 1                                     ; 0-Equil, 1-NonEquil
               UB_Global = 70                                    ; default 70 MeV/u
             MinZ_Global = 2                                     ; default Z>=29
        ChargeStateOptim = 1                                     ; 0-No, 1-Yes
         ZmQ_AfterReactn = 0                                     ; default 0 (full stripped)
             EPAX_p_Norm = 1
               EPAX_p_Un = 1.65
              EPAX_p_Up0 = 1.79
              EPAX_p_Up1 = 0.00472
              EPAX_p_Up2 = -1.3e-5 
                EPAX_p_H = 1

[fission]
         FisAngDistShape = 0                                     ; 0-isotropic; 1-anisotropic
     FisMomCutForAngDist = 2                                     ; 0-dont use;  1-use just MatrixKinematics; 2-use for all; (default 2)
      OddEvenCorrections = 1                                     ; 0-dont use;  1-use
 PostScissionEvaporation = 1                                     ; 0-dont use;  1-use
   DeexcitFunctionPoints = 0                                     ; 0- average deexcitation energy;  1- 3 points; 2 - manually
           FisEXmanually = 20                                    ; Excitation energy manually
           FisCSmanually = 1000                                  ; Cross section manually
            FisTXEmethod = 1                                     ; 0-from Edissipated, 1 from Q-value
                   Fis_f = 0.0045                                ; default 0.0045
              FisEXsigma = 5.5                  MeV              ; default 5.5
            FisCS_Global = 1e-11    
               FisCS_TKE = 1e-8     
                FisBeta1 = 0.625                                 ; deformation of light fragment
                FisBeta2 = 0.625                                 ; deformation of heavy fragment
                FisTKE_d = 2                    fm               ; d-param in Wilkins formula
              FisBetaFit = 1                                     ; 0-manual, 1-fit
                      N0 = 83                                    ; default 82
                     dU0 = -2.65                                 ; default -2.5
                      C0 = 0.7                                   ; default 1.4
                   cpol0 = 0.65                                  ; default 0.65
                  width0 = 0.63                                  ; default 0.63
                      N1 = 90                                    ; default 90
                     dU1 = -3.8                                  ; default -5.5
                      C1 = 0.15                                  ; default 0.16
                   cpol1 = 0.55                                  ; default 0.55
                  width1 = 0.97                                  ; default 0.97

[charge_suppression]
                 FragInd = 1e-3     
               FragTotal = 1e-5     
                 BeamInd = 1e-20    
               BeamTotal = 1e-20    

[convolution]
        Convolution mode = 1                                     ; 0-Qgg, 1-Surface, 2-E* per Abraded nucleon
                 Sigma_0 = 91.5   
                 Sigma_1 = 91.5   
                 Sigma_2 = 125     
              CoefConv_0 = 3.344 
              CoefConv_1 = 3     
              CoefConv_2 = 1     
             ShiftConv_0 = 0.158 
             ShiftConv_1 = 0.149 
             ShiftConv_2 = -1     

[evaporation]
          NP evaporation = 32                                    ; Number of points in distribution
               NPevapFis = 8                                     ; Number of points in distribution
              EvapMethod = 2
        StateDensityMode = 2                                     ; 0, 1+pairing, 2+shell
      EvapUnstableNuclei = 1                                     ; 0 - only stable,1 +unstable
              Tunnelling = 1
          AvoidUnboundCS = 1
       ProtectedChannels = 1
           R_Evaporation = 5.7                  fm               ; correction for the effective Coulomb barrier
         Mode_Apf_manual = 0                                     ; 1-manual, 0-auto
             Energy_in_T = 2                                     ; default 2
     EvaporationVelocity = 0                                     ; 0 - quality, 1 -fast
        DeltaOddEvenEvap = 12    
     DeltaOddEvenFission = 14    
   BreakupTemperature250 = 4.7  
   BreakupTemperature150 = 5.9  
   BreakupTemperature050 = 8    
      BreakupDiffuseness = 0.05 
      DissipationKramers = 0
 DissipationStepFunction = 1
         DissipationBeta = 1                                     ; default 2.0
                 mode_1n = 1
                 mode_2n = 0
                 mode_1p = 1
                 mode_2p = 0
                  mode_a = 1
                  mode_d = 0
                  mode_t = 0
                mode_3he = 0
                mode_fis = 1
             mode_brk_up = 1
              mode_gamma = 0

[fission_barrier]
    FissionBarrierFactor = 1    
      FissionBarrierMode = 1                                     ; #0-4
      OddEvenCorrections = 1
        ShellCorrections = 1
             FB_InOutMax = 2                                     ; #0-2 - in/out/max
             ModeForUser = 1                                     ; #0-2
           NdeltaOddEven = 2.5  
           ZdeltaOddEven = 9    

[excitation_energy]
           AbrasionModel = 0                                     ; 0-Geometrical, 1-exponentional
       GeomAA_Correction = 1                                     ; 0 - don't use,1 - use -default
          Thermalization = 0
          ThermaTimeCoef = 3e+0                                  ; 2.1e-22 MeV *s/e(t)
            AbraExpSlope = 0.363
                Friction = 0                                     ; 0 - off,1 - on
          Ev_A_SigmaCoef = 9.6  
         G_FrictionCoef1 = 6.5  
         G_FrictionCoef2 = 0.5  
           G_FactorCoef1 = 1.5  
           G_FactorCoef2 = 2.5  
               DepthHole = 40    
          EnergyCoef_CB0 = 0       
          EnergyCoef_CB1 = 13.3     
          EnergyCoef_CB2 = 0       
           SigmaCoef_CB0 = 0       
           SigmaCoef_CB1 = 9.6     
           SigmaCoef_CB2 = 0       
              D_MeanTemp = 13       
               AA_factor = 1       
          ApplyLimitTemp = 0

[evapauto]
                  tun_a0 = -0.61392
                  tun_a1 = 0.44559
                  tun_a2 = 0.12008
                 A_Bound = 300
               A_Pairing =   1

[plot]
            Start target = RF                                    ; Detector & RF      
            Start of TOF = T1
            Stop  of TOF = T1
         dE-detector-1st = M1
         dE-detector-2nd = M2
            TKE-detector = M2
                PlotBrho = S11
               PlotWedge = S22
              X-detector = M1
              Y-detector = M1
                 Tilting = M1
                 Stopper = n
                RO_Wedge = n
          ConditionBlock = A0
          Plot threshold = 1e-10                pps              ; minimal value for plot scale
     Shift of TOF for RF = 0                    ns               ; for dE-TOF plot with RF
  Fraction of RF trigger = 2
            UseCondition = 0
         TKE_calibration = 1,1,0,MeV

[cs_file]
              UserDiffCS = 5                                     ; Number of User Diff CS saved in this file
         AppendOverwrite = 1
          AttachedInside = 1
            ShowCSinPlot = 1
                    Chi2 = 1
              CSfilename = 

[sec_reactions]
        NP sec.reactions = 16                                    ; Number of points in distribution
     Secondary reactions = 0
         fiss_FilterUse0 = 1
         fiss_FilterUse1 = 1
         fiss_FilterUse2 = 1
            fiss_ellipse = 5
          fiss_NdeltaTop = 0
          fiss_ZdeltaTop = 0
          fiss_NdeltaBot = 25
          fiss_ZdeltaBot = 20
         frag_FilterUse0 = 3
         frag_FilterUse1 = 3
         frag_FilterUse2 = 3
            frag_ellipse = 4
          frag_NdeltaTop = 5
          frag_ZdeltaTop = 5
          frag_NdeltaBot = 6
          frag_ZdeltaBot = 6

[abrasion_fission]
                HML_show = 7                                     ; HML-bits
            AF_Ex_choice = 0
             BoundaryLow = 40                   MeV              
            BoundaryHigh = 180                  MeV              
                Velocity = 1                                     ; Calculat fissile nuclei speed
           LowEx_nucleus = 47Ca20+                               ; Mass ElementName Charge+ Beam
                 L_CS_Ex = 3.000e+02 25.00 5.00                  ; mb, MeV, Mev
           MidEx_nucleus = 42Ar18+                               ; Mass ElementName Charge+ Beam
                 M_CS_Ex = 1.000e+03 100.00 5.00                 ; mb, MeV, Mev
          HighEx_nucleus = 36S 16+                               ; Mass ElementName Charge+ Beam
                 H_CS_Ex = 8.000e+02 250.00 5.00                 ; mb, MeV, Mev

[gamma_detection]
                   coef0 = 1.39905 
                   coef1 = 0.69523 
                   coef2 = -5.92199 
                   coef3 = 1       
                   coef4 = 0.269   
                    area = 38.81                cm^2             
                distance = 20.4                 cm               
                geom_eff = 1                    %                
                    mode = 2                                     ; 0-area,1-dist,2-geom
               threshold = 100                  keV              
                   start = 0                    mks              
                    gate = 10                   mks              
             Energy_cell = 1330                 keV              
             Refer_GperF = 0.01                 g/f              
                 UseGeom = 0
               UseEnergy = 1

[sec_target]
                     NP2 = 16                                    ; Dimension
                tertiary = 0
                  method = 0                                     ; 0-distribution, 1-gauss, 2-d4
               threshold = 1e-10
                   Pr_z0 = 1
                   Pr_z1 = 100
                   Pr_n0 = 0
                   Pr_n1 = 200
                   Dr_z0 = 1
                   Dr_z1 = 8
                   Dr_n0 = 0
                   Dr_n1 = 10

[cross sections]
1     19O   = 36.9873 0 7
2     17N   = 0.430457 0 7
3     16C   = 1.88363 0 7
4     18O   = 2.05786e+11 0 7
5     20O   = 22.1174 0 7

[previous]
                 Lowerst = 12B 5+                                ; Mass ElementName Charge+ Beam
                 Highest = 18O 8+                                ; Mass ElementName Charge+ Beam

[finger]
             Diffuseness = 0.01                                  ; default 0.01
             Suppression = 1e+12                                 ; default 1e12

[MC_options]
                   dXsel = 8
                   dYsel = 6
                   dZsel = 4
                  dAZQ_X = 1
                  dAZQ_Y = 5
                  dAZQ_Z = 7
                  dVEL_X = 1
                  dVEL_Y = 0
                  dVEL_Z = 0
               dIso_mode = 1
               strag_ang = 1
               strag_ene = 1
               strag_lat = 0
            MCresolution = 1
            XYresolution = 1
                  defect = 1
                  charge = 1
           loss_reaction = 1
            reaction_ang = 0
            reaction_mom = 0
               HighOrder = 1
                  CS_use = 1
           envelope_show = 0
                use_bore = 1
             use_ang_acc = 1
          XY_orientation = 0
            outside_cikl = 1
        MC_outside_sigma = 1
               dP_option = 0
              Radialsign = 1
             ReverseFlag = 0
              AZQ_Xsigma = 0.1   
              AZQ_Ysigma = 0.1   
                 G1_gate = 0 1 -1000.0000 1000.0000
                 G2_gate = 0 0 -100.0000 100.0000
                 G3_gate = 0 0 -100.0000 100.0000
                 G4_gate = 0 0 -100.0000 100.0000
            G1_component = 0 0,S22,R1,R1                         ; mode,RF_TOF,BP,TOFstart,TOFstop
            G2_component = 0 0,R1,R1,R1
            G3_component = 0 0,R1,R1,R1
            G4_component = 0 0,R1,R1,R1

[Levmar_fit]
                   Niter = 1000                                  ; # iterations
               UseBounds = 1
                 Example = 4                                     ; 0-15
                    opt0 = 1e-3     
                    opt1 = 1e-15    
                    opt2 = 1e-15    
                    opt3 = 1e-20    
                    opt4 = 1e-6     


{============================= BLOCK D1 - Dipole ======================================}

[D1_General]
                    Name = tuning,1                              ; Name of Block, Constant name 1/0
               Available = 0
                  Length = 2.356194             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0
             Before_Quad = 0                                     ; number of quadrupoles before optic device
              After_Quad = 0                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings

[D1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[D1_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D1_AngAcceptance]
                   X-Use = 1
                 X-Value = 26                   mrad             ; acceptance
                   Y-Use = 1
                 Y-Value = 72                   mrad             ; acceptance
                   Shape = 0                                     ; 0 - rectangle, 1- ellipse

[D1_DipoleSettings]
                    Brho = 1.00764              Tm               ; magnetic rigidity
                   Angle = -0.0001              degrees          
                  Radius = 3                    m                

[D1_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1
                 GapVert = 0                    cm               ; code 16.5
                      K1 = 0.7                                   ; code 16.7
                      K2 = 4.4                                   ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Entrance Use 1/0
          UseExitFringeF = 1                                     ; Exit Use 1/0


{============================= BLOCK S1 - Drift ======================================}

[S1_General]
                    Name = dr1,1                                 ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.95                 m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S1_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Bottom,B-limit,Top,T-limit

[S1_optics]
                    row1 = +1.00000e+00,+9.50000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+9.50000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S1_AngAcceptance]
                   X-Use = 0
                 X-Value = 174.532925           mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 349.06585            mrad             ; acceptance
                   Shape = 0                                     ; 0 - rectangle, 1- ellipse

[S1_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.95                 m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0                    Tm               ; refBrho
          CorrespondErho = 0e+0                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK S2 - Drift ======================================}

[S2_General]
                    Name = Q1,1                                  ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.4                  m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1
               B-fitting = 1 0 -100.000 100.000                  ; B-field: Use, Gate, Bounds

[S2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Bottom,B-limit,Top,T-limit

[S2_optics]
                    row1 = +1.53233e+00,+4.68733e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +2.87588e+00,+1.53233e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+5.48027e-01,+3.37693e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-2.07190e+00,+5.48027e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S2_optics2]
                   row11 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = -5.75177e-03,-7.20986e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row21 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = -3.31824e-02,-5.75177e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,+4.14380e-03,+5.92414e-04,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,+1.70843e-02,+4.14380e-03,+0.00000e+00,+0.00000e+00
                   row51 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[S2_AngAcceptance]
                   X-Use = 0
                 X-Value = 226                  mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 113                  mrad             ; acceptance
                   Shape = 0                                     ; 0 - rectangle, 1- ellipse

[S2_DriftSettings]
                    Mode = 2                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 2                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.4                  m                
               Leff_coef = -0.68                1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = -5.591232            KG               
                  Radius = 8                    cm               ; half-aperture
       Include 2nd order = 1
          CorrespondBrho = 1.139125             Tm               ; refBrho
          CorrespondErho = 0e+0                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 8                    cm               ; half-aperture


{============================= BLOCK S3 - Drift ======================================}

[S3_General]
                    Name = dr2,1                                 ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.07                 m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-2.00,-75.0,2.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-2.00,-75.0,2.00,75.0               ; joint,Bottom,B-limit,Top,T-limit

[S3_optics]
                    row1 = +1.00000e+00,+7.00000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+7.00000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S3_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S3_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.07                 m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0                    Tm               ; refBrho
          CorrespondErho = 0e+0                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK S4 - Drift ======================================}

[S4_General]
                    Name = Q2,1                                  ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.4                  m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1
               B-fitting = 1 0 -100.000 100.000                  ; B-field: Use, Gate, Bounds

[S4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Bottom,B-limit,Top,T-limit

[S4_optics]
                    row1 = +5.89593e-01,+3.43614e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = -1.89858e+00,+5.89593e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.47557e+00,+4.61598e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+2.55048e+00,+1.47557e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S4_optics2]
                   row11 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +3.79717e-03,+5.38884e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row21 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = +1.60083e-02,+3.79717e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,-5.10096e-03,-6.43145e-04,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-2.90584e-02,-5.10096e-03,+0.00000e+00,+0.00000e+00
                   row51 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[S4_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S4_DriftSettings]
                    Mode = 2                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 2                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.4                  m                
               Leff_coef = -0.67                1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5.035241             KG               
                  Radius = 8                    cm               ; half-aperture
       Include 2nd order = 1
          CorrespondBrho = 1.139125             Tm               ; refBrho
          CorrespondErho = 1e-2                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 8                    cm               ; half-aperture


{============================= BLOCK S5 - Drift ======================================}

[S5_General]
                    Name = dr3,1                                 ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.075                m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S5_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Bottom,B-limit,Top,T-limit

[S5_optics]
                    row1 = +1.00000e+00,+7.50000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+7.50000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S5_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S5_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.075                m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0.001                Tm               ; refBrho
          CorrespondErho = 1e-2                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK S6 - Drift ======================================}

[S6_General]
                    Name = dr4,1                                 ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.094                m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S6_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-35.0,3.00,35.0               ; joint,Bottom,B-limit,Top,T-limit

[S6_optics]
                    row1 = +1.00000e+00,+9.40000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+9.40000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S6_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S6_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.094                m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0.001                Tm               ; refBrho
          CorrespondErho = 1e-2                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK D2 - Dipole ======================================}

[D2_General]
                    Name = D1,1                                  ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.422701             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1
             Before_Quad = 0                                     ; number of quadrupoles before optic device
              After_Quad = 0                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = A1900/A1900_D1-Z026.cal

[D2_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-1.00,-75.0,1.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-35.0,3.00,35.0               ; joint,Bottom,B-limit,Top,T-limit

[D2_optics]
                    row1 = +9.23880e-01,+4.11920e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+8.19360e-01
                    row2 = +0.00000e+00,+1.08239e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+4.14214e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+4.22700e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-3.84810e-01,+8.37340e-01,+0.00000e+00,+0.00000e+00
                    row5 = -3.82680e-01,-8.19400e-02,+0.00000e+00,+0.00000e+00,+1.00000e+00,-1.07810e-01
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D2_optics2]
                   row11 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = +3.83883e-04,+5.13725e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,-1.15056e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,-2.30038e-04,-1.38205e-04,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +1.52480e-03,+3.40455e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,-7.82825e-03
                   row21 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = -1.16714e-05,-2.42641e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,-3.06687e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+1.46431e-04,-1.45210e-04,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = -2.32159e-05,-1.72608e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,-4.49747e-02
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = -1.47262e-04,-4.58357e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +3.20436e-04,+5.41823e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.07808e-04,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = +0.00000e+00,+4.00188e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = +0.00000e+00,+5.32110e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,+3.84814e-03,+1.58513e-03,+0.00000e+00,+0.00000e+00
                   row51 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,-1.77761e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D2_AngAcceptance]
                   X-Use = 0
                 X-Value = 200                  mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 125                  mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D2_DipoleSettings]
                    Brho = 1.14305              Tm               ; magnetic rigidity
                   Angle = 22.5                 degrees          
                  Radius = 1.0764               m                

[D2_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1
                 GapVert = 4                    cm               ; code 16.5
                      K1 = 0                                     ; code 16.7
                      K2 = 0                                     ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 22.5                 deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Entrance Use 1/0
          UseExitFringeF = 1                                     ; Exit Use 1/0


{============================= BLOCK S7 - Drift ======================================}

[S7_General]
                    Name = dr5,1                                 ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.1162               m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S7_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-35.0,3.00,35.0               ; joint,Bottom,B-limit,Top,T-limit

[S7_optics]
                    row1 = +1.00000e+00,+1.16200e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+1.16200e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S7_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S7_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.1162               m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0                    Tm               ; refBrho
          CorrespondErho = 0e+0                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK S8 - Drift ======================================}

[S8_General]
                    Name = dr6,1                                 ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.1162               m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S8_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-35.0,3.00,35.0               ; joint,Bottom,B-limit,Top,T-limit

[S8_optics]
                    row1 = +1.00000e+00,+1.16200e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+1.16200e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S8_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S8_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.1162               m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0.001                Tm               ; refBrho
          CorrespondErho = 1e-2                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK D3 - Dipole ======================================}

[D3_General]
                    Name = D2,1                                  ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.422701             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1
             Before_Quad = 0                                     ; number of quadrupoles before optic device
              After_Quad = 0                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings

[D3_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-35.0,3.00,35.0               ; joint,Bottom,B-limit,Top,T-limit

[D3_optics]
                    row1 = +1.08239e+00,+4.11920e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-8.19361e-01
                    row2 = +0.00000e+00,+9.23880e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-3.82683e+00
                    row3 = +0.00000e+00,+0.00000e+00,+8.37339e-01,+4.22701e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-3.84814e-01,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +4.14214e-01,+8.19361e-02,+0.00000e+00,+0.00000e+00,+1.00000e+00,-1.07808e-01
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D3_optics2]
                   row11 = -1.47262e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = -3.02460e-04,-3.78495e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,+1.43236e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,-2.77773e-04,-4.20292e-05,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +0.00000e+00,+3.13556e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+7.88176e-03
                   row21 = +5.66684e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = +2.20893e-04,+1.91342e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,+5.66684e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,-2.20893e-04,+1.91342e-04,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+3.82683e-02
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = +3.18790e-04,-4.28545e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = -4.81590e-04,-8.19361e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,+1.58513e-03,+1.07808e-04,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = -3.30288e-04,-2.30113e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = -2.99008e-04,+3.62807e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,+3.84814e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row51 = -3.04989e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +1.30602e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,+2.27932e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,-1.30602e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = -3.15301e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D3_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D3_DipoleSettings]
                    Brho = 1.14305              Tm               ; magnetic rigidity
                   Angle = -22.5                degrees          
                  Radius = 1.0764               m                

[D3_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1
                 GapVert = 4                    cm               ; code 16.5
                      K1 = 0                                     ; code 16.7
                      K2 = 0                                     ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 22.5                 deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Entrance Use 1/0
          UseExitFringeF = 1                                     ; Exit Use 1/0


{============================= BLOCK S9 - Drift ======================================}

[S9_General]
                    Name = d7,1                                  ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.094                m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S9_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-35.0,3.00,35.0               ; joint,Bottom,B-limit,Top,T-limit

[S9_optics]
                    row1 = +1.00000e+00,+9.40000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+9.40000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S9_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S9_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.094                m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0.001                Tm               ; refBrho
          CorrespondErho = 1e-2                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK S10 - Drift ======================================}

[S10_General]
                    Name = d8,1                                  ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.2                  m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S10_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-35.0,3.00,35.0               ; joint,Bottom,B-limit,Top,T-limit

[S10_optics]
                    row1 = +1.00000e+00,+2.00000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+2.00000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S10_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S10_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.2                  m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0.001                Tm               ; refBrho
          CorrespondErho = 1e-2                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK F1 - Fit ======================================}

[F1_General]
                    Name = FocX,1                                ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0                    m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0

[F1_FitSettings]
              Constraint = 1                                     ; 0-41
                 Operand = 0                                     ; 0-2
                   Value = 0       
               Precision = 0.001   
                  Active = 1
                SecOrder = 111                                   ; T***


{============================= BLOCK F2 - Fit ======================================}

[F2_General]
                    Name = FocY,1                                ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0                    m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0

[F2_FitSettings]
              Constraint = 15                                    ; 0-41
                 Operand = 0                                     ; 0-2
                   Value = 0       
               Precision = 0.01    
                  Active = 1
                SecOrder = 111                                   ; T***


{============================= BLOCK A1 - FaradayCup ======================================}

[A1_General]
                    Name = FaradayCup 1,0                        ; Name of Block, Constant name 1/0
               Available = 0
                  Length = 0                    m                ; Length block for optical blocks

[A1_Compound]
               contents1 = 0,74,1,183.85                         ; Nomer,Z,Atoms,Mass
               thickness = 0,10000000000,19.35,0,0,0             ; State,Thickness,density,angle,SolidGas,..
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1
             ResolutionE = 0,0.5                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[A1_BlockCalibration]
                     TOF = 1,1,0,ns
                      dE = 1,1,0,MeV
                       X = 1,1,0,mm
                       Y = 1,1,0,mm


{============================= BLOCK S11 - Drift ======================================}

[S11_General]
                    Name = Slits,1                               ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0                    m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S11_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 1,1,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 0,-10.00,-75.0,10.00,75.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,0                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-35.0,20.00,35.0             ; joint,Bottom,B-limit,Top,T-limit

[S11_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S11_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S11_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0.001                Tm               ; refBrho
          CorrespondErho = 1e-2                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK W1 - Wedge ======================================}

[W1_General]
                    Name = Wedge 1,0                             ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0                    m                ; Length block for optical blocks

[W1_Compound]
               contents1 = 0,4,1,9.012                           ; Nomer,Z,Atoms,Mass
               thickness = 1,0,1.848,0,0,0                       ; State,Thickness,density,angle,SolidGas,..
                  Defect = 0,0.1                                 ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1

[W1_ProdTarget]
              ProdTarget = 0

[W1_WedgeSettings]
             ProfileMode = 0                                     ; 0-Wedge,1-Homo,2-Curved,3-Custom
    PhysProfileDesirable = 0                                     ; 0-Achrom,1-Monoch,2-user-defined
                   Angle = 0.61353              mrad             ; wedge slope for the mode (0-Wedge)
               Direction = 0                                     ; x=0, y=1
       CalculateForBlock = FP slits
           DirectReverse = 0                                     ; 0-direct, 1-LISE reverse, 2-COSY
        ExternalInternal = 1                                     ; external=0 / internal=1
            ReadInternal = 0
       CustExternalInter = 1                                     ; external=0 / internal=1
           CustReadInter = 0
                  Porder = 2                                     ; polynom order 1-4
                   coef0 = 0e+0                 mm^(+1)          
                   coef1 = 0e+0                 mm^(+0)          
                   coef2 = 0e+0                 mm^(-1)          
                   coef3 = 0e+0                 mm^(-2)          
                   coef4 = 0e+0                 mm^(-3)          
         MatrixElement66 = 1                                     ; d/d matrix, default 1


{============================= BLOCK S12 - Drift ======================================}

[S12_General]
                    Name = d9,1                                  ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.2                  m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S12_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-35.0,3.00,35.0               ; joint,Bottom,B-limit,Top,T-limit

[S12_optics]
                    row1 = +1.00000e+00,+2.00000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+2.00000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S12_AngAcceptance]
                   X-Use = 1
                 X-Value = 43                   mrad             ; acceptance
                   Y-Use = 1
                 Y-Value = 30                   mrad             ; acceptance
                   Shape = 0                                     ; 0 - rectangle, 1- ellipse

[S12_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.2                  m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0.001                Tm               ; refBrho
          CorrespondErho = 1e-2                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK S13 - Drift ======================================}

[S13_General]
                    Name = d10,1                                 ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.094                m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S13_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-35.0,3.00,35.0               ; joint,Bottom,B-limit,Top,T-limit

[S13_optics]
                    row1 = +1.00000e+00,+9.40000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+9.40000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S13_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S13_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.094                m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0.001                Tm               ; refBrho
          CorrespondErho = 1e-2                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK D4 - Dipole ======================================}

[D4_General]
                    Name = D3,1                                  ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.422701             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1
             Before_Quad = 0                                     ; number of quadrupoles before optic device
              After_Quad = 0                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings

[D4_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-35.0,3.00,35.0               ; joint,Bottom,B-limit,Top,T-limit

[D4_optics]
                    row1 = +9.23880e-01,+4.11920e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,-8.19361e-01
                    row2 = +0.00000e+00,+1.08239e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-4.14214e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+4.22701e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-3.84814e-01,+8.37339e-01,+0.00000e+00,+0.00000e+00
                    row5 = +3.82683e-01,+8.19361e-02,+0.00000e+00,+0.00000e+00,+1.00000e+00,-1.07808e-01
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D4_optics2]
                   row11 = +1.36052e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = -3.23223e-04,-2.43266e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,-1.15056e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,-2.30038e-04,-5.62692e-05,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +1.40414e-03,+2.86657e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+7.93526e-03
                   row21 = +5.23548e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = -2.83776e-04,+1.10913e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,-3.06687e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+1.46431e-04,+2.69004e-04,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = +1.15031e-03,-1.20285e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+4.39340e-02
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = -1.47262e-04,-4.58357e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = -4.44931e-04,-1.09690e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.07808e-04,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = +0.00000e+00,+4.00188e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = +2.94524e-04,+5.95170e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,+3.84814e-03,+1.58513e-03,+0.00000e+00,+0.00000e+00
                   row51 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,+1.77761e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D4_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D4_DipoleSettings]
                    Brho = 1.14305              Tm               ; magnetic rigidity
                   Angle = -22.5                degrees          
                  Radius = 1.0764               m                

[D4_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1
                 GapVert = 4                    cm               ; code 16.5
                      K1 = 0                                     ; code 16.7
                      K2 = 0                                     ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 0                    deg              ; code 2.0 - entrance
              Beta2angle = 22.5                 deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Entrance Use 1/0
          UseExitFringeF = 1                                     ; Exit Use 1/0


{============================= BLOCK S14 - Drift ======================================}

[S14_General]
                    Name = dr11,1                                ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.1162               m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S14_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-35.0,3.00,35.0               ; joint,Bottom,B-limit,Top,T-limit

[S14_optics]
                    row1 = +1.00000e+00,+1.16200e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+1.16200e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S14_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S14_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.1162               m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0.001                Tm               ; refBrho
          CorrespondErho = 1e-2                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK S15 - Drift ======================================}

[S15_General]
                    Name = dr12,1                                ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.1162               m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S15_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-35.0,3.00,35.0               ; joint,Bottom,B-limit,Top,T-limit

[S15_optics]
                    row1 = +1.00000e+00,+1.16200e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+1.16200e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S15_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S15_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.1162               m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0                    Tm               ; refBrho
          CorrespondErho = 0e+0                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK D5 - Dipole ======================================}

[D5_General]
                    Name = D4,1                                  ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.422701             m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1
             Before_Quad = 0                                     ; number of quadrupoles before optic device
              After_Quad = 0                                     ; number of quadrupoles after  optic device
             QB_DontDraw = 0
             QA_DontDraw = 0
                     ZmQ = 0                                     ;  Z - Q  = charge state settings
        Calibration file = A1900/A1900_D1-Z026.cal

[D5_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-1.00,-75.0,1.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-35.0,3.00,35.0               ; joint,Bottom,B-limit,Top,T-limit

[D5_optics]
                    row1 = +1.08239e+00,+4.11920e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+8.19361e-01
                    row2 = +0.00000e+00,+9.23880e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+3.82683e+00
                    row3 = +0.00000e+00,+0.00000e+00,+8.37339e-01,+4.22701e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-3.84814e-01,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = -4.14214e-01,-8.19361e-02,+0.00000e+00,+0.00000e+00,+1.00000e+00,-1.07808e-01
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[D5_optics2]
                   row11 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = +4.33777e-04,+3.78495e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,+1.31103e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,-2.46243e-04,-1.23965e-04,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +0.00000e+00,+3.13556e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,-7.88176e-03
                   row21 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = +7.36309e-05,-1.91342e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,-7.36309e-05,-1.91342e-04,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,-3.82683e-02
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = +0.00000e+00,-4.91606e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +3.46837e-04,+8.19361e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,+1.58513e-03,+1.07808e-04,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = -3.30288e-04,-2.30113e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = -2.99008e-04,+3.62807e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,+3.84814e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row51 = +3.04989e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = -1.30602e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,-2.27932e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+1.30602e-05,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +3.15301e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[D5_AngAcceptance]
                   X-Use = 0
                 X-Value = 200                  mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 125                  mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[D5_DipoleSettings]
                    Brho = 1.14305              Tm               ; magnetic rigidity
                   Angle = 22.5                 degrees          
                  Radius = 1.0764               m                

[D5_DipoleTransport]
                 Code4_N = 0                                     ; default 0. code 4. n
                 Code4_B = 0                                     ; default 0. code 4. b
         Calculate2Order = 1
                 GapVert = 4                    cm               ; code 16.5
                      K1 = 0                                     ; code 16.7
                      K2 = 0                                     ; code 16.8
       EntranceCurvature = 0                    1/m              ; 1/R1 - code 16.12
           ExitCurvature = 0                    1/m              ; 1/R2 - code 16.13
              Beta1angle = 22.5                 deg              ; code 2.0 - entrance
              Beta2angle = 0                    deg              ; code 2.0 - exit
          UseFringeField = 1                                     ; Entrance Use 1/0
          UseExitFringeF = 1                                     ; Exit Use 1/0


{============================= BLOCK S16 - Drift ======================================}

[S16_General]
                    Name = dr13,1                                ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.094                m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S16_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-3.00,-35.0,3.00,35.0               ; joint,Bottom,B-limit,Top,T-limit

[S16_optics]
                    row1 = +1.00000e+00,+9.40000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+9.40000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S16_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S16_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.094                m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0.001                Tm               ; refBrho
          CorrespondErho = 1e-2                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK S17 - Drift ======================================}

[S17_General]
                    Name = dr14,1                                ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.075                m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S17_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Bottom,B-limit,Top,T-limit

[S17_optics]
                    row1 = +1.00000e+00,+7.50000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+7.50000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S17_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S17_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.075                m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0.001                Tm               ; refBrho
          CorrespondErho = 1e-2                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK S18 - Drift ======================================}

[S18_General]
                    Name = Q3,1                                  ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.4                  m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1
               B-fitting = 1 1 3.000 4.500                       ; B-field: Use, Gate, Bounds

[S18_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Bottom,B-limit,Top,T-limit

[S18_optics]
                    row1 = +5.89593e-01,+3.43614e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = -1.89858e+00,+5.89593e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.47557e+00,+4.61598e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+2.55048e+00,+1.47557e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S18_optics2]
                   row11 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = +3.79717e-03,+5.38884e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row21 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = +1.60083e-02,+3.79717e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,-5.10096e-03,-6.43145e-04,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,-2.90584e-02,-5.10096e-03,+0.00000e+00,+0.00000e+00
                   row51 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[S18_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S18_DriftSettings]
                    Mode = 2                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 2                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.4                  m                
               Leff_coef = -0.67                1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 5.052594             KG               
                  Radius = 8                    cm               ; half-aperture
       Include 2nd order = 1
          CorrespondBrho = 1.14305              Tm               ; refBrho
          CorrespondErho = 1e-2                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 8                    cm               ; half-aperture


{============================= BLOCK S19 - Drift ======================================}

[S19_General]
                    Name = dr15,1                                ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.07                 m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S19_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-2.00,-75.0,2.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-2.00,-75.0,2.00,75.0               ; joint,Bottom,B-limit,Top,T-limit

[S19_optics]
                    row1 = +1.00000e+00,+7.00000e-02,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+7.00000e-02,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S19_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S19_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.07                 m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0                    Tm               ; refBrho
          CorrespondErho = 0e+0                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK S20 - Drift ======================================}

[S20_General]
                    Name = Q4,1                                  ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.4                  m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 1                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1
               B-fitting = 1 1 -5.000 -3.500                     ; B-field: Use, Gate, Bounds

[S20_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Bottom,B-limit,Top,T-limit

[S20_optics]
                    row1 = +1.53227e+00,+4.68726e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +2.87555e+00,+1.53227e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+5.48068e-01,+3.37699e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,-2.07173e+00,+5.48068e-01,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S20_optics2]
                   row11 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row12 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row13 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row14 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row15 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row16 = -5.75110e-03,-7.20907e-04,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row21 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row22 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row23 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row24 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row25 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row26 = -3.31782e-02,-5.75110e-03,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row31 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row32 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row33 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row34 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row35 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row36 = +0.00000e+00,+0.00000e+00,+4.14345e-03,+5.92360e-04,+0.00000e+00,+0.00000e+00
                   row41 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row42 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row43 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row44 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row45 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row46 = +0.00000e+00,+0.00000e+00,+1.70832e-02,+4.14345e-03,+0.00000e+00,+0.00000e+00
                   row51 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row52 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row53 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row54 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row55 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row56 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row61 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row62 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row63 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row64 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row65 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                   row66 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00

[S20_AngAcceptance]
                   X-Use = 0
                 X-Value = 226                  mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 113                  mrad             ; acceptance
                   Shape = 0                                     ; 0 - rectangle, 1- ellipse

[S20_DriftSettings]
                    Mode = 2                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 2                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.4                  m                
               Leff_coef = -0.67                1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = -5.609937            KG               
                  Radius = 8                    cm               ; half-aperture
       Include 2nd order = 1
          CorrespondBrho = 1.14305              Tm               ; refBrho
          CorrespondErho = 0e+0                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 8                    cm               ; half-aperture


{============================= BLOCK S21 - Drift ======================================}

[S21_General]
                    Name = dr16,1                                ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0.95                 m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S21_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 1                                     ; 0-slits, 1-ellipse
                X_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-7.00,-75.0,7.00,75.0               ; joint,Bottom,B-limit,Top,T-limit

[S21_optics]
                    row1 = +1.00000e+00,+9.50000e-01,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+9.50000e-01,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S21_AngAcceptance]
                   X-Use = 0
                 X-Value = 112                  mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 230                  mrad             ; acceptance
                   Shape = 0                                     ; 0 - rectangle, 1- ellipse

[S21_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0.95                 m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0                    Tm               ; refBrho
          CorrespondErho = 0e+0                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK F3 - Fit ======================================}

[F3_General]
                    Name = FP FocX,1                             ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0                    m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0

[F3_FitSettings]
              Constraint = 1                                     ; 0-41
                 Operand = 0                                     ; 0-2
                   Value = 0       
               Precision = 0.001   
                  Active = 1
                SecOrder = 111                                   ; T***


{============================= BLOCK F4 - Fit ======================================}

[F4_General]
                    Name = FP FocY,1                             ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0                    m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0

[F4_FitSettings]
              Constraint = 15                                    ; 0-41
                 Operand = 0                                     ; 0-2
                   Value = 0       
               Precision = 0.01    
                  Active = 1
                SecOrder = 111                                   ; T***


{============================= BLOCK F5 - Fit ======================================}

[F5_General]
                    Name = FP dipX,1                             ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0                    m                ; Length block for optical blocks
               SE_method = 0                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 0

[F5_FitSettings]
              Constraint = 5                                     ; 0-41
                 Operand = 0                                     ; 0-2
                   Value = 0       
               Precision = 0.01    
                  Active = 1
                SecOrder = 111                                   ; T***


{============================= BLOCK S22 - Drift ======================================}

[S22_General]
                    Name = FP slits,1                            ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0                    m                ; Length block for optical blocks
               SE_method = 1                                     ; 0: S-block, 1: E-block
             SecondOrder = 0                                     ; Exist - 1, Non - 0
              ThirdOrder = 0                                     ; Number of lines
           CalculateAuto = 1                                     ; 0/1/2  nothing, keep_matrix, keep_field
        RemotePermission = 1

[S22_slits]
              SlitsShape = 0                                     ; 0-slits, 1-ellipse
           ApertureShape = 0                                     ; 0-slits, 1-ellipse
                X_action = 1,1,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  X_size = 1,-15.00,-50.0,15.00,50.0             ; joint,Left,L-limit,Right,R-limit
                Y_action = 0,0,1                                 ; Use 1/0, Show 1/0, UseApp 1/0
                  Y_size = 1,-20.00,-50.0,20.00,50.0             ; joint,Bottom,B-limit,Top,T-limit

[S22_optics]
                    row1 = +1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row2 = +0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row3 = +0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00
                    row4 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00,+0.00000e+00
                    row5 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00,+0.00000e+00
                    row6 = +0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+0.00000e+00,+1.00000e+00

[S22_AngAcceptance]
                   X-Use = 0
                 X-Value = 1000                 mrad             ; acceptance
                   Y-Use = 0
                 Y-Value = 1000                 mrad             ; acceptance
                   Shape = 1                                     ; 0 - rectangle, 1- ellipse

[S22_DriftSettings]
                    Mode = 1                                     ; 4-finger, E-Quad 3, M-Quad 2, Stand 1, Beamline 0
              ShowLength = 0                                     ; I 3 / B 2 / Brho 1 / Length 0
        Length_effective = 0                    m                
               Leff_coef = 0.7                  1                
               Leff_mode = 0                                     ; file-3, calc-2, manually-1, keep-0
           MagneticField = 0                    KG               
                  Radius = 5                    cm               ; half-aperture
       Include 2nd order = 0
          CorrespondBrho = 0.001                Tm               ; refBrho
          CorrespondErho = 1e-2                 J/c              ; for e-quad refErho
                 Voltage = 0                    kV               ; for e-quad
           sextMagnField = 0                    KG               
                 sextRad = 5                    cm               ; half-aperture


{============================= BLOCK M1 - Material ======================================}

[M1_General]
                    Name = DE,1                                  ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0                    m                ; Length block for optical blocks

[M1_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,200,2.321,0,0,0                     ; State,Thickness,density,angle,SolidGas,..
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1
             ResolutionE = 0,0.5                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M1_BlockCalibration]
                     TOF = 1,1,0,ns
                      dE = 1,1,0,MeV
                       X = 1,1,0,mm
                       Y = 1,1,0,mm

[M1_ProdTarget]
              ProdTarget = 0


{============================= BLOCK M2 - Material ======================================}

[M2_General]
                    Name = Eres,1                                ; Name of Block, Constant name 1/0
               Available = 1
                  Length = 0                    m                ; Length block for optical blocks

[M2_Compound]
               contents1 = 0,14,1,28.086                         ; Nomer,Z,Atoms,Mass
               thickness = 0,1000,2.321,0,0,0                    ; State,Thickness,density,angle,SolidGas,..
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1
             ResolutionE = 0,0.5                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M2_BlockCalibration]
                     TOF = 1,1,0,ns
                      dE = 1,1,0,MeV
                       X = 1,1,0,mm
                       Y = 1,1,0,mm

[M2_ProdTarget]
              ProdTarget = 0


{============================= BLOCK M3 - Material ======================================}

[M3_General]
                    Name = IC Window,1                           ; Name of Block, Constant name 1/0
               Available = 0
                  Length = 0                    m                ; Length block for optical blocks

[M3_Compound]
               contents1 = 0,6,22,12.011                         ; Nomer,Z,Atoms,Mass
               contents2 = 1,1,10,1.008                          ; Nomer,Z,Atoms,Mass
               contents3 = 2,7,2,14.007                          ; Nomer,Z,Atoms,Mass
               contents4 = 3,8,4,15.999                          ; Nomer,Z,Atoms,Mass
               thickness = 1,1.14,1.42,0,0,0                     ; State,Thickness,density,angle,SolidGas,..
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1
             ResolutionE = 0,0.5                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M3_BlockCalibration]
                     TOF = 1,1,0,ns
                      dE = 1,1,0,MeV
                       X = 1,1,0,mm
                       Y = 1,1,0,mm

[M3_ProdTarget]
              ProdTarget = 0


{============================= BLOCK M4 - Material ======================================}

[M4_General]
                    Name = IC Dead Section,1                     ; Name of Block, Constant name 1/0
               Available = 0
                  Length = 0                    m                ; Length block for optical blocks

[M4_Compound]
               contents1 = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
               contents2 = 1,9,4,18.998                          ; Nomer,Z,Atoms,Mass
               thickness = 4,10,0.003659,0,1,0                   ; State,Thickness,density,angle,SolidGas,..
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1
             ResolutionE = 0,0.5                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M4_BlockCalibration]
                     TOF = 1,1,0,ns
                      dE = 1,1,0,MeV
                       X = 1,1,0,mm
                       Y = 1,1,0,mm

[M4_ProdTarget]
              ProdTarget = 0


{============================= BLOCK M5 - Material ======================================}

[M5_General]
                    Name = IC Section 1,1                        ; Name of Block, Constant name 1/0
               Available = 0
                  Length = 0                    m                ; Length block for optical blocks

[M5_Compound]
               contents1 = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
               contents2 = 1,9,4,18.998                          ; Nomer,Z,Atoms,Mass
               thickness = 4,39.5,0.003659,0,1,0                 ; State,Thickness,density,angle,SolidGas,..
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1
             ResolutionE = 0,0.5                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M5_BlockCalibration]
                     TOF = 1,1,0,ns
                      dE = 1,1,0,MeV
                       X = 1,1,0,mm
                       Y = 1,1,0,mm

[M5_ProdTarget]
              ProdTarget = 0


{============================= BLOCK M6 - Material ======================================}

[M6_General]
                    Name = IC Section 2,1                        ; Name of Block, Constant name 1/0
               Available = 0
                  Length = 0                    m                ; Length block for optical blocks

[M6_Compound]
               contents1 = 0,6,1,12.011                          ; Nomer,Z,Atoms,Mass
               contents2 = 1,9,4,18.998                          ; Nomer,Z,Atoms,Mass
               thickness = 4,39.5,0.003659,0,1,0                 ; State,Thickness,density,angle,SolidGas,..
                  Defect = 1,0                                   ; [0] choice - % or micron at 0 degree,  [1]=value; 
        Use for Q-states = 1
             ResolutionE = 0,0.5                                 ; [0] choice - % or MeV,  [1]=value; 
             Resolution2 = 0.1,0.3,0.3          ns,mm,mm         ; Time&X&Y space

[M6_BlockCalibration]
                     TOF = 1,1,0,ns
                      dE = 1,1,0,MeV
                       X = 1,1,0,mm
                       Y = 1,1,0,mm

[M6_ProdTarget]
              ProdTarget = 0


{============================= User Diff CS ======================================}

[DiffCS0000]
CorrelatedTo=0
Filename=o18dp_10.dat.txt
Comment=10 MeV/u o18dp from global with 0.66 and 1.0 s factors!!!!!!!!!!!!
Ex12 = 0.000 0.000
NofPoints  = 181
0        88.1123 
1        87.4696 
2        85.5741 
3        82.5271 
4        78.4817 
5        73.6421 
6        68.2342 
7        62.4965 
8        56.6646 
9        50.9498 
10       45.5345 
11       40.5577 
12       36.1171 
13       32.2663 
14       29.0171 
15       26.3496 
16       24.2137 
17       22.54   
18       21.2483 
19       20.2526 
20       19.4685 
21       18.8182 
22       18.2348 
23       17.6637 
24       17.061  
25       16.4003 
26       15.6631 
27       14.8456 
28       13.9511 
29       12.9916 
30       11.9821 
31       10.9428 
32       9.89489 
33       8.85906 
34       7.85531 
35       6.90116 
36       6.0114  
37       5.1974  
38       4.46742 
39       3.82624 
40       3.27553 
41       2.81384 
42       2.43765 
43       2.14123 
44       1.91734 
45       1.75769 
46       1.65325 
47       1.59496 
48       1.57369 
49       1.58072 
50       1.60804 
51       1.64848 
52       1.69564 
53       1.74415 
54       1.78981 
55       1.82917 
56       1.85998 
57       1.88051 
58       1.89014 
59       1.88871 
60       1.87657 
61       1.85469 
62       1.82419 
63       1.78642 
64       1.74294 
65       1.69534 
66       1.64501 
67       1.59352 
68       1.54211 
69       1.49191 
70       1.44391 
71       1.39887 
72       1.35727 
73       1.31964 
74       1.28595 
75       1.2564  
76       1.23081 
77       1.20892 
78       1.19048 
79       1.175   
80       1.16208 
81       1.15115 
82       1.1419  
83       1.13368 
84       1.12612 
85       1.11872 
86       1.11122 
87       1.10328 
88       1.09453 
89       1.08486 
90       1.07407 
91       1.0621  
92       1.04888 
93       1.03439 
94       1.01876 
95       1.00199 
96       0.984222
97       0.965645
98       0.946352
99       0.926477
100      0.906266
101      0.885882
102      0.865474
103      0.845246
104      0.825198
105      0.805592
106      0.786494
107      0.768037
108      0.750231
109      0.733116
110      0.716785
111      0.701249
112      0.686508
113      0.672543
114      0.659328
115      0.646851
116      0.635051
117      0.623891
118      0.613338
119      0.60332 
120      0.593797
121      0.584726
122      0.576062
123      0.567762
124      0.559787
125      0.552122
126      0.544727
127      0.537591
128      0.530698
129      0.524041
130      0.517616
131      0.511417
132      0.505451
133      0.499712
134      0.494209
135      0.488943
136      0.483917
137      0.479136
138      0.474599
139      0.470302
140      0.466237
141      0.46241 
142      0.458797
143      0.455397
144      0.452194
145      0.449181
146      0.446336
147      0.443649
148      0.441107
149      0.438692
150      0.436399
151      0.434198
152      0.4321  
153      0.430085
154      0.428152
155      0.426288
156      0.424494
157      0.422777
158      0.421139
159      0.419566
160      0.418073
161      0.416663
162      0.41534 
163      0.414103
164      0.41296 
165      0.411907
166      0.410952
167      0.410085
168      0.409315
169      0.408631
170      0.408037
171      0.407525
172      0.407092
173      0.406732
174      0.406436
175      0.4062  
176      0.406015
177      0.405877
178      0.405779
179      0.405725
180      0.405709

[DiffCS0001]
CorrelatedTo=1
Filename=ca48d3he_10.dat.txt
Comment=c48d3he 3 16 3 15!!!!!!!!!!!!
Ex12 = 0.000 0.000
NofPoints  = 181
0        0.221707
1        0.219554
2        0.216004
3        0.210438
4        0.20335 
5        0.195349
6        0.187143
7        0.179429
8        0.172822
9        0.16784 
10       0.16483 
11       0.163929
12       0.165066
13       0.167963
14       0.172159
15       0.177055
16       0.181977
17       0.18619 
18       0.18906 
19       0.189963
20       0.188472
21       0.18433 
22       0.177455
23       0.167973
24       0.156188
25       0.142568
26       0.127702
27       0.112252
28       0.096911
29       0.0823521
30       0.0691916
31       0.0579448
32       0.0490045
33       0.0426261
34       0.0389175
35       0.0378454
36       0.0392456
37       0.0428462
38       0.0482843
39       0.0551392
40       0.0629583
41       0.0712763
42       0.0796494
43       0.0876643
44       0.0949619
45       0.101243
46       0.106275
47       0.109898
48       0.112019
49       0.112611
50       0.111705
51       0.109382
52       0.105762
53       0.101003
54       0.095284
55       0.0887992
56       0.0817469
57       0.0743309
58       0.06675 
59       0.059187
60       0.0518167
61       0.0447927
62       0.0382481
63       0.0322946
64       0.0270224
65       0.0224938
66       0.0187512
67       0.0158118
68       0.0136699
69       0.0123  
70       0.0116568
71       0.011679
72       0.0122903
73       0.0134034
74       0.0149234
75       0.0167496
76       0.0187798
77       0.0209128
78       0.0230525
79       0.0251076
80       0.026997
81       0.0286519
82       0.0300139
83       0.0310386
84       0.0316964
85       0.0319701
86       0.0318575
87       0.0313669
88       0.0305205
89       0.0293509
90       0.0278951
91       0.0262009
92       0.0243159
93       0.0222969
94       0.0201942
95       0.0180614
96       0.015949
97       0.0139025
98       0.0119629
99       0.0101654
100      0.00853881
101      0.00710463
102      0.00587781
103      0.00486627
104      0.00407174
105      0.00348969
106      0.00311015
107      0.00291874
108      0.00289709
109      0.00302394
110      0.00327592
111      0.00362817
112      0.00405536
113      0.00453263
114      0.00503576
115      0.00554225
116      0.0060314
117      0.00648474
118      0.00688694
119      0.00722492
120      0.007489
121      0.0076725
122      0.00777128
123      0.00778446
124      0.00771317
125      0.00756151
126      0.00733491
127      0.00704136
128      0.00668939
129      0.00628926
130      0.00585121
131      0.0053862
132      0.0049052
133      0.00441865
134      0.00393622
135      0.00346735
136      0.00301961
137      0.00259987
138      0.00221379
139      0.00186522
140      0.00155706
141      0.00129072
142      0.00106641
143      0.000883301
144      0.000739561
145      0.000632656
146      0.000559498
147      0.000516601
148      0.000500414
149      0.000507393
150      0.00053419
151      0.000577906
152      0.000636043
153      0.000706742
154      0.000788696
155      0.000881273
156      0.000984336
157      0.00109827
158      0.0012239
159      0.00136218
160      0.00151428
161      0.00168125
162      0.001864
163      0.00206281
164      0.00227772
165      0.00250803
166      0.00275253
167      0.00300872
168      0.00327405
169      0.00354487
170      0.0038167
171      0.00408501
172      0.00434467
173      0.0045902
174      0.00481624
175      0.00501782
176      0.00519007
177      0.00532863
178      0.00543025
179      0.00549235
180      0.00551317

[DiffCS0002]
CorrelatedTo=2
Filename=o18d3he_15.dat.txt
Comment=o18d3he 2 states 4 6!!!!!!!!!!!!
Ex12 = 0.000 0.000
NofPoints  = 181
0        0.136052
1        0.135159
2        0.264713
3        0.467297
4        0.724443
5        1.01301 
6        1.30781 
7        1.58382 
8        1.81884 
9        1.99531 
10       2.10179 
11       2.13356 
12       2.09258 
13       1.98668 
14       1.82842 
15       1.63349 
16       1.4188  
17       1.20104 
18       0.995139
19       0.813142
20       0.663505
21       0.550909
22       0.47629 
23       0.437311
24       0.429043
25       0.444747
26       0.476762
27       0.517271
28       0.558978
29       0.595695
30       0.622658
31       0.636706
32       0.636324
33       0.621471
34       0.593393
35       0.554307
36       0.507052
37       0.454793
38       0.400703
39       0.347705
40       0.298312
41       0.254461
42       0.217493
43       0.188104
44       0.166431
45       0.152105
46       0.144347
47       0.142117
48       0.14421 
49       0.149342
50       0.15629 
51       0.16392 
52       0.171267
53       0.177575
54       0.182283
55       0.185052
56       0.18573 
57       0.184335
58       0.181019
59       0.176036
60       0.169711
61       0.162381
62       0.154401
63       0.146116
64       0.137813
65       0.129734
66       0.122075
67       0.114971
68       0.108501
69       0.102697
70       0.0975525
71       0.0930305
72       0.0890711
73       0.0856018
74       0.0825462
75       0.0798268
76       0.077374
77       0.0751276
78       0.0730405
79       0.0710754
80       0.0692084
81       0.0674263
82       0.0657253
83       0.0641074
84       0.0625781
85       0.0611462
86       0.0598197
87       0.0586053
88       0.057506
89       0.0565206
90       0.0556448
91       0.0548681
92       0.0541773
93       0.0535551
94       0.0529829
95       0.0524392
96       0.0519018
97       0.0513502
98       0.0507651
99       0.0501281
100      0.049426
101      0.0486475
102      0.0477866
103      0.0468392
104      0.0458076
105      0.0446968
106      0.043515
107      0.0422722
108      0.0409837
109      0.0396624
110      0.0383254
111      0.0369882
112      0.0356656
113      0.0343739
114      0.0331244
115      0.0319285
116      0.0307951
117      0.0297302
118      0.0287386
119      0.0278197
120      0.0269742
121      0.0261989
122      0.0254881
123      0.0248368
124      0.0242365
125      0.0236804
126      0.0231597
127      0.0226665
128      0.0221934
129      0.0217343
130      0.021282
131      0.0208325
132      0.020383
133      0.0199296
134      0.0194725
135      0.0190111
136      0.0185463
137      0.0180802
138      0.0176148
139      0.0171531
140      0.0166988
141      0.0162544
142      0.015824
143      0.0154105
144      0.0150167
145      0.0146467
146      0.0143017
147      0.0139859
148      0.0137016
149      0.0134508
150      0.0132357
151      0.0130588
152      0.0129236
153      0.0128315
154      0.0127861
155      0.0127893
156      0.0128431
157      0.0129502
158      0.0131116
159      0.0133292
160      0.0136038
161      0.0139342
162      0.0143196
163      0.0147565
164      0.0152421
165      0.0157713
166      0.0163365
167      0.0169319
168      0.0175464
169      0.0181722
170      0.0187965
171      0.0194087
172      0.0199982
173      0.0205515
174      0.0210577
175      0.0215071
176      0.0218893
177      0.0221957
178      0.0224198
179      0.0225556
180      0.0226015

[DiffCS0003]
CorrelatedTo=3
Filename=/Users/raisor/inflight/lise_files/ar40_elastic.txt
Comment= !!!!!!!!!
Ex12 = 0.000 0.000
NofPoints  = 32
0        3.78207e+14
0.5      3.647e+14
1        6.294e+08
2        3.962e+07
3        7.875e+06
4        2.49e+06
5        1.01e+06
6        477800  
7        250900  
8        142000  
9        85070   
10       53340   
11       34720   
12       23340   
13       16150   
14       11470   
15       8358    
16       6236    
17       4763    
18       3721    
19       2969    
20       2419    
21       2007    
22       1695    
23       1453    
24       1262    
25       1108    
26       982.2   
27       877.3   
28       788.5   
29       712.1   
180      0       

[DiffCS0004]
CorrelatedTo=4
Filename=19O_gs.txt
Comment= J.Wiza et al., PhysRev 143 (1966) 676 -- Ground state  18O(p,d)19O"	!!!DEGREES	ARB-UNITS!!!!!!
Ex12 = 0.000 0.000
NofPoints  = 25
0        10.0837 
4.913    9.603   
13.27    9.6774  
20.843   9.166   
29.181   8.7714  
37.36    4.6251  
46.009   2.628   
52.808   1.7652  
59.254   1.5278  
67.596   1.2505  
76.33    1.2466  
91.113   0.6146  
96.809   0.6121  
103.64   0.4527  
111.24   0.5665  
119.21   0.563   
126.43   0.5597  
133.26   0.5176  
139.71   0.3975  
147.69   0.5111  
154.9    0.5079  
160.98   0.5443  
167.81   0.4239  
174.65   0.5381  
180      0.533014
